`homework_ndarray_251118.ipynb`에 작성하세요. #25

<h3>🧪 NumPy 실습문제 1: <code inline="">ndarray</code> 생성과 인덱싱 기초</h3>
<p><strong>문제 설명</strong>:<br>
학생 4명의 국어, 수학, 영어 점수가 다음과 같을 때, NumPy를 사용하여 2차원 배열로 만들고 특정 학생의 성적이나 특정 과목의 점수를 추출하라.</p>

이름 | 국어 | 수학 | 영어
-- | -- | -- | --
철수 | 87 | 90 | 85
영희 | 92 | 88 | 79
민수 | 76 | 95 | 90
수진 | 88 | 84 | 92


<p><strong>요구사항</strong>:</p>
<ol>
<li>
<p>위 표를 기반으로 2차원 배열 생성 (<code inline="">ndarray</code>)</p>
</li>
<li>
<p>영희의 성적을 모두 출력</p>
</li>
<li>
<p>모든 학생의 수학 점수만 출력</p>
</li>
<li>
<p>철수와 수진의 영어 점수만 출력 (fancy indexing 활용)</p>
</li>
</ol>
<hr>
<h3>🧪 NumPy 실습문제 2: 슬라이싱과 브로드캐스팅</h3>
<p><strong>문제 설명</strong>:<br>
다음과 같은 1~12까지의 수로 구성된 배열을 3x4 형태로 만들고, 특정 조건에 맞는 부분 배열을 수정하라.</p>
<pre><code class="language-python">np.arange(1, 13).reshape(3, 4)
</code></pre>
<p><strong>요구사항</strong>:</p>
<ol>
<li>
<p>배열을 슬라이싱하여 마지막 열만 추출</p>
</li>
<li>
<p>두 번째 행의 모든 값에 10을 더하라 (브로드캐스팅 사용)</p>
</li>
<li>
<p>2~3열만 추출하여 출력하라</p>
</li>
</ol>
<hr>
<h3>🧪 NumPy 실습문제 3: 조건 인덱싱 + 통계 연산</h3>
<p><strong>문제 설명</strong>:<br>
100명 학생의 시험 점수가 0~100 사이의 난수로 주어질 때, 특정 기준으로 필터링하고 통계값을 계산하라.</p>
<pre><code class="language-python">np.random.seed(0)
scores = np.random.randint(0, 101, size=100)
</code></pre>
<p><strong>요구사항</strong>:</p>
<ol>
<li>
<p>90점 이상인 학생의 수는 몇 명인가?</p>
</li>
<li>
<p>50점 미만 점수만 추출하여 평균을 구하라</p>
</li>
<li>
<p>전체 평균, 최대값, 최소값을 구하되 <code inline="">np.mean</code>, <code inline="">np.max</code>, <code inline="">np.min</code>을 사용하라</p>
</li>
</ol>
<hr>
<h3>🧪 NumPy 실습문제 4: 다차원 배열 연산 및 axis 활용</h3>
<p><strong>문제 설명</strong>:<br>
5일간의 3개 센서 측정값이 다음과 같이 주어졌을 때, 센서별 평균과 날짜별 합계를 구하라.</p>
<pre><code class="language-python">data = np.array([
    [23, 25, 22],  # Day 1
    [24, 26, 23],
    [22, 24, 21],
    [25, 27, 24],
    [23, 25, 22]
])
</code></pre>
<p><strong>요구사항</strong>:</p>
<ol>
<li>
<p>각 센서의 5일간 평균을 구하라 (axis=0)</p>
</li>
<li>
<p>각 날짜별 측정값 합계를 구하라 (axis=1)</p>
</li>
<li>
<p>전체 데이터의 최소/최대값을 구하라</p>
</li>
</ol>
<hr>
<h3>🧪 NumPy 실습문제 5: 행렬 곱과 브로드캐스팅</h3>
<p><strong>문제 설명</strong>:<br>
2x3 행렬 A와 3x2 행렬 B를 생성하여 행렬 곱을 수행하고, 결과에 브로드캐스팅을 적용하라.</p>
<pre><code class="language-python">A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0], [0, 1], [1, 1]])
</code></pre>
<p><strong>요구사항</strong>:</p>
<ol>
<li>
<p>A와 B의 행렬곱 결과를 구하라 (<code inline="">@</code> 또는 <code inline="">np.dot</code>)</p>
</li>
<li>
<p>결과 행렬에 <code inline="">np.array([10, 100])</code>을 더하라 (브로드캐스팅 이용)</p>
</li>
<li>
<p>최종 결과의 shape를 확인하라</p>
</li>
</ol>

# 1. 2차원 배열 생성

In [4]:
import numpy as np

scores = np.array([
    [87, 90, 85],  # 철수
    [92, 88, 79],  # 영희
    [76, 95, 90],  # 민수
    [88, 84, 92]   # 수진
])

scores


array([[87, 90, 85],
       [92, 88, 79],
       [76, 95, 90],
       [88, 84, 92]])

# 2. 영희의 성적 모두 출력

In [5]:
scores[1]

array([92, 88, 79])

# 3. 모든 학생의 수학 점수만 출력

In [6]:
scores[:, 1]

array([90, 88, 95, 84])

# 4. 철수와 수진의 영어 점수만 출력 (Fancy Indexing)

In [7]:
scores[[0, 3], 2]

array([85, 92])

# NumPy 실습문제 2: 슬라이싱과 브로드캐스팅

## 배열 생성

In [8]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 1. 마지막 열만 추출

In [9]:
arr[:, -1]

array([ 4,  8, 12])

## 2. 두 번째 행에 10 더하기 (브로드캐스팅)

In [10]:
arr[1] += 10
arr

array([[ 1,  2,  3,  4],
       [15, 16, 17, 18],
       [ 9, 10, 11, 12]])

## 3. 2~3열만 추출

In [11]:
arr[:, 1:3]

array([[ 2,  3],
       [16, 17],
       [10, 11]])

# NumPy 실습문제 3: 조건 인덱싱 + 통계 연산

## 점수 데이터 생성

In [12]:
np.random.seed(0)
scores = np.random.randint(0, 101, size=100)

## 1. 90점 이상 학생 수

In [13]:
np.sum(scores >= 90)

np.int64(5)

## 2. 50점 미만 점수 평균

In [14]:
low_scores = scores[scores < 50]
np.mean(low_scores)

np.float64(24.75)

## 3. 전체 평균 / 최대 / 최소

In [15]:
np.mean(scores), np.max(scores), np.min(scores)

(np.float64(48.75), np.int32(100), np.int32(0))

# NumPy 실습문제 4: 다차원 배열 연산 및 axis

## 데이터 생성

In [16]:
data = np.array([
    [23, 25, 22],
    [24, 26, 23],
    [22, 24, 21],
    [25, 27, 24],
    [23, 25, 22]
])


## 1. 센서별 평균 (axis=0)

In [17]:
np.mean(data, axis=0)

array([23.4, 25.4, 22.4])

## 2. 날짜별 합계 (axis=1)

In [18]:
np.sum(data, axis=1)

array([70, 73, 67, 76, 70])

## 3. 전체 최소 / 최대

In [19]:
np.min(data), np.max(data)

(np.int64(21), np.int64(27))

# NumPy 실습문제 5: 행렬 곱과 브로드캐스팅

## 행렬 정의

In [20]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 0],
              [0, 1],
              [1, 1]])

## 1. 행렬 곱

In [21]:
C = A @ B
C

array([[ 4,  5],
       [10, 11]])

## 2. 브로드캐스팅으로 값 더하기

In [22]:
C + np.array([10, 100])

array([[ 14, 105],
       [ 20, 111]])

## 3. 최종 결과 shape

In [23]:
C.shape

(2, 2)