`homework_torch_tensor_251215.ipynb`에 작성하세요. # 30

### 💡 조건

* 입력: 샘플 수 6개, 특성 수 10개
* 은닉층: 입력 10 → 출력 8 (활성화 함수: `tanh`)
* 출력층: 입력 8 → 출력 4 (활성화 함수: `softmax`)
* PyTorch 사용



### 문제 1. 직접 가중치/절편을 선언하고 순전파 계산

다음 조건에 맞게 PyTorch 텐서를 사용하여 forward 계산을 수동으로 구현하세요.

**📌 요구사항**

1. 입력 `X`는 `torch.randn(6, 10)` 으로 생성한다.
2. `W1`, `b1`, `W2`, `b2`도 torch의 `randn`을 이용해 직접 정의한다.
3. 은닉층에서는 `tanh`, 출력층에서는 `softmax`를 사용한다.
4. 최종 결과는 `(6, 4)` 크기의 확률 벡터이어야 한다.

### 문제 2. 위 네트워크를 PyTorch 모델 클래스로 작성

다음 조건에 맞는 `nn.Module` 클래스를 작성하세요.

📌 요구사항

1. `__init__`에 `nn.Linear(10, 8)`과 `nn.Linear(8, 4)`를 정의한다.
2. `forward`에서는 `tanh` → `softmax` 순으로 활성화 함수를 적용한다.
3. 임의의 입력 `X = torch.randn(6, 10)`을 모델에 넣어 출력 결과를 확인한다.



### ✨ 문제3. 층별 가중치/편향 출력

모델 내 가중치와 편향 값을 확인하고 출력하세요.




In [1]:
!pip install torch torchvision torchaudio

  Using cached torch-2.9.1-cp312-cp312-win_amd64.whl.metadata (30 kB)
  Using cached torchvision-0.24.1-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.9.1-cp312-cp312-win_amd64.whl (110.9 MB)
Using cached torchvision-0.24.1-cp312-cp312-win_amd64.whl (4.3 MB)
   ---------------------------------------- 0.0/665.3 kB ? eta -:--:--
   ---------------------------------------- 665.3/665.3 kB 8.6 MB/s  0:00:00
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)

   ---------------------------------------- 0/8 [mpmath]
   ---------------------------------------- 0/8 [mpmath]
   ---------------------------------------- 0/8 [mpmath]
   ---------------------------------------- 0/8 [mpmath

### 💡 조건

* 입력: 샘플 수 6개, 특성 수 10개
* 은닉층: 입력 10 → 출력 8 (활성화 함수: `tanh`)
* 출력층: 입력 8 → 출력 4 (활성화 함수: `softmax`)
* PyTorch 사용



### 문제 1. 직접 가중치/절편을 선언하고 순전파 계산

다음 조건에 맞게 PyTorch 텐서를 사용하여 forward 계산을 수동으로 구현하세요.

**📌 요구사항**

1. 입력 `X`는 `torch.randn(6, 10)` 으로 생성한다.
2. `W1`, `b1`, `W2`, `b2`도 torch의 `randn`을 이용해 직접 정의한다.
3. 은닉층에서는 `tanh`, 출력층에서는 `softmax`를 사용한다.
4. 최종 결과는 `(6, 4)` 크기의 확률 벡터이어야 한다.

In [2]:
import torch
import torch.nn.functional as F

# 1️⃣ 입력 데이터
X = torch.randn(6, 10)   # (샘플 6, 특성 10)

# 2️⃣ 가중치와 편향 직접 선언
W1 = torch.randn(10, 8)
b1 = torch.randn(8)

W2 = torch.randn(8, 4)
b2 = torch.randn(4)

# 3️⃣ 순전파 계산
z1 = X @ W1 + b1         # (6, 8)
a1 = torch.tanh(z1)     # tanh 활성화

z2 = a1 @ W2 + b2       # (6, 4)
output = F.softmax(z2, dim=1)  # softmax

# 4️⃣ 결과 확인
print(output.shape)
print(output)


torch.Size([6, 4])
tensor([[2.9554e-01, 5.2298e-01, 3.1490e-03, 1.7833e-01],
        [6.8788e-02, 8.4180e-01, 2.0699e-02, 6.8712e-02],
        [3.7734e-02, 1.2334e-03, 6.0147e-03, 9.5502e-01],
        [5.3514e-01, 2.7353e-01, 2.7603e-02, 1.6373e-01],
        [7.6055e-01, 1.0868e-03, 5.0621e-04, 2.3786e-01],
        [1.3055e-03, 6.2568e-03, 1.3985e-04, 9.9230e-01]])


### 💡 조건

* 입력: 샘플 수 6개, 특성 수 10개
* 은닉층: 입력 10 → 출력 8 (활성화 함수: `tanh`)
* 출력층: 입력 8 → 출력 4 (활성화 함수: `softmax`)
* PyTorch 사용

### 문제 2. 위 네트워크를 PyTorch 모델 클래스로 작성

다음 조건에 맞는 `nn.Module` 클래스를 작성하세요.

📌 요구사항

1. `__init__`에 `nn.Linear(10, 8)`과 `nn.Linear(8, 4)`를 정의한다.
2. `forward`에서는 `tanh` → `softmax` 순으로 활성화 함수를 적용한다.
3. 임의의 입력 `X = torch.randn(6, 10)`을 모델에 넣어 출력 결과를 확인한다.


In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 8)
        self.fc2 = nn.Linear(8, 4)

    def forward(self, x):
        x = torch.tanh(self.fc1(x))
        x = F.softmax(self.fc2(x), dim=1)
        return x

# 모델 생성
model = SimpleNN()

# 입력 데이터
X = torch.randn(6, 10)

# 순전파
output = model(X)

print(output.shape)
print(output)


torch.Size([6, 4])
tensor([[0.2371, 0.2746, 0.3138, 0.1744],
        [0.1925, 0.2543, 0.3924, 0.1607],
        [0.2657, 0.2290, 0.3286, 0.1767],
        [0.2308, 0.2406, 0.3444, 0.1843],
        [0.2294, 0.1900, 0.2936, 0.2870],
        [0.2321, 0.2773, 0.3036, 0.1871]], grad_fn=<SoftmaxBackward0>)


### 💡 조건

* 입력: 샘플 수 6개, 특성 수 10개
* 은닉층: 입력 10 → 출력 8 (활성화 함수: `tanh`)
* 출력층: 입력 8 → 출력 4 (활성화 함수: `softmax`)
* PyTorch 사용

### ✨ 문제3. 층별 가중치/편향 출력

모델 내 가중치와 편향 값을 확인하고 출력하세요.

In [4]:
# 첫 번째 층
print("FC1 Weight:\n", model.fc1.weight)
print("FC1 Bias:\n", model.fc1.bias)

# 두 번째 층
print("FC2 Weight:\n", model.fc2.weight)
print("FC2 Bias:\n", model.fc2.bias)


FC1 Weight:
 Parameter containing:
tensor([[ 0.2508, -0.1946, -0.0098,  0.0540,  0.1771,  0.1210,  0.1819, -0.1421,
         -0.0810,  0.3146],
        [ 0.1549, -0.2603,  0.1399,  0.0026, -0.1646,  0.2749, -0.2678, -0.1942,
         -0.2211,  0.2938],
        [-0.3121, -0.1783, -0.1435,  0.0104,  0.1425, -0.0818,  0.3134,  0.1751,
          0.1619, -0.0792],
        [ 0.2789, -0.1714, -0.1592, -0.0486,  0.2420, -0.2535,  0.1313, -0.2941,
         -0.1973,  0.0064],
        [-0.2790, -0.1143, -0.0777, -0.1490, -0.1164,  0.0747, -0.2847, -0.1588,
          0.0306, -0.1637],
        [ 0.2598,  0.0487,  0.0603,  0.1812,  0.0985, -0.2631, -0.1398,  0.2711,
          0.1731,  0.1311],
        [ 0.0434, -0.1140,  0.1342, -0.1390, -0.1040,  0.2011,  0.1205, -0.1289,
         -0.0382,  0.1186],
        [-0.1701,  0.1012,  0.2046,  0.2302,  0.2303, -0.1963,  0.0416,  0.2189,
          0.0324, -0.0151]], requires_grad=True)
FC1 Bias:
 Parameter containing:
tensor([ 0.0705, -0.1192,  0.0008, -0.0